# demo-loans.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-eureka-client-loan
  namespace: under76-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team5-eureka-client-loan
  template:
    metadata:
      labels:
        app: team5-eureka-client-loan
    spec:
      containers:
      - name: team5-eureka-client-loan
        image: k8s-vga-worker1:5000/img-team5-eureka-client-loan:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: team5-eureka-client-loan
  namespace: under76-test
spec:
  selector:
    app: team5-eureka-client-loan
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
      nodePort: 30295
  type: NodePort
